bookstore/urls.py
from django.urls import path
from . import views

app_name = 'bookstore'

urlpatterns = [
    path('', views.index, name='bookstore'),
]

loginhello/urls.py
from django.urls import path, include
from . import views
# from django.contrib.auth.urls

app_name = 'loginhello'

urlpatterns = [
    path('login/', views.views_login, name='login'),
    path('logout/', views.views_logout, name='logout'),
    path('hello/', views.hello, name='hello'),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bookstore.urls")),
    path('accounts/', include('loginhello.urls')),
]

bookstore/models.py
from django.db import models

# Create your models here.

loginhello/models.py
from django.db import models

# Create your models here.

bookstore/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

loginhello/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def hello(request):
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_visits': num_visits,
    }

    return render(request, 'loginhello/hello.html', context=context)

def views_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            
            return redirect('loginhello:hello')
    else:
        form = AuthenticationForm()

    return render(request, 'loginhello/login.html', { 'form': form })

def views_logout(request):
    logout(request)
    return redirect('loginhello:hello')

bookstore/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>toko buku</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="{% static 'script.js' %}"></script>
</head>
<body>
    
    <h1 class="heading">my bookstore</h1>
    <div class="searchbox">
        <input id="search_box" type="text">
        <input type="submit" value="Cari buku.." id="search_button">
    </div>

    <table id="results" class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Book Cover</th>
                <th scope="col">Details</th>
                <th scope="col">Author(s)</th>
            </tr>
        </thead>
    </table>

</body>
</html>

loginhello/templates/loginhello/hello.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <title>Hello, you</title>
</head>
<body>
    <div class="hello-form">
        {% if user.is_authenticated %}
        <h1>Hello, {{ user }}!</h1>
        <p>Have a nice day. <br><br>You have visited this page {{ num_visits }} time(s).</p>
        <a href="{% url 'loginhello:logout' %}">
            <input type="button" value="Logout" class="logbtn" id="logout_button">
        </a>
        {% else %}
        <h2>You are not logged in. <br> Please login first.</h2>
        <a href="{% url 'loginhello:login' %}">
            <input type="button" value="Login" class="logbtn" id="relogin">
        </a>
        {% endif %}
    </div>
</body>
</html>

loginhello/templates/loginhello/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    
	<link rel="stylesheet" href="{% static 'style2.css' %}">
    <title>Login Page</title>
</head>
<body>
    <form action="{% url 'loginhello:login' %}" method="POST" class="login-form">
        {% csrf_token %}
        
        <h1>Login</h1>
        
        <div class="txtb">
            {{ form.username }}
            <span data-placeholder="Username"></span>
        </div>

        <div class="txtb">
            {{ form.password }}
            <span data-placeholder="Password"></span>
        </div>

        <button type="submit" id="login_button" class="logbtn">Login</button>
    </form>

    <script type="text/javascript">
        $(".txtb input").on("focus", function(){
            $(this).addClass("focus");
        });

        $(".txtb input").on("blur", function(){
            if($(this).val() == "")
            $(this).removeClass("focus");
        });
    </script>

</body>
</html>